version: "3.9"

services:
    postgres:
        image: postgres:14.6
        restart: unless-stopped
        networks:
            - next
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: piquetdestream_api
        volumes:
            - postgres:/var/lib/postgresql/data
        ports:
            - "127.0.0.1:5432:5432"

networks:
    next:


volumes:
    postgres:
