name: Pull Request
on:
  pull_request:
    branches: [master, staging]

jobs:
  runLinters:
    name: Run linters
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Node.js dependencies
        run: npm ci

      - name: Build the app
        env:
          SKIP_ENV_VALIDATION: 1
        run: npm run build

      - name: Run TypeScript type-checking
        run: npm run type-check

      - name: Run ESLint
        uses: wearerequired/lint-action@v1
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          # Enable linters
          eslint: true
          eslint_args: --ext ts,tsx --fix ./src/**/*
          prettier: true
          prettier_args: --write ./src/**/*.(ts|tsx|css|json)

  buildAndTest:
    name: Build and test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Build the app
        env:
          SKIP_ENV_VALIDATION: 1
        run: npm run build

      - name: Archive production artifacts
        uses: actions/upload-artifact@v3
        with:
          name: dist-${{ matrix.node-version }}
          path: |
            dist
